### ISSUE TITLE
Rename create message and delete message

### ISSUE THREAD

**Issue by devshorts** [tronroy/cassieq-client#2]
I think it will make more sense for queue consumers if create message is named to "put message" or "publish message", and delete message is renamed to "ack message". it's not a big deal but those terms are more common in other queue systems so new users may feel more accustomed to that nomenclature

**Comment by devshorts** [comment]
Also I should mention great work with this project!

**Comment by tronroy** [comment]
Thanks!

That's a good idea. I could alias the methods to allow for multiple names. Or do you think only one name should be enforced?

Are there any other things that could use renaming?

**Comment by devshorts** [comment]
I'd just say to make there be only one way otherwise multiple names may be confusing.  Didn't see anything off the top of my head that needed renaming, those two stuck out at me.

**Comment by tronroy** [comment]
See pull request https://github.com/tronroy/cassieq-client/pull/3
